### ISSUE TITLE
"Download with Aria2" does not work

### ISSUE THREAD

**Issue by egothor** [baptistecdr/aria2-extensions#1]
Addon is installed and configured. I can see previous downloads via extension icon, and I can also add new tasks there.

Unfortunately, the context menu item "Download with Aria2" does not work. It only shouts "The download cannot be sent to Aria2.".

I use Firefox 70.0 (Fedora/x86_64).

**Comment by baptistecdr** [comment]
Hi egothor,
Thank you for reporting the issue.
Did you try to restart Firefox ? Because when the settings is updated, the background page don't catch the change. It's a bug that I will patch very soon.
Otherwise, can you post the error that you get :
* Go to about:debugging#/runtime/this-firefox
* Click 'Inspect' on Aria2c Integration

**Comment by egothor** [comment]
Yes, that's true. I did try the download operation just after the installation and it failed. Now it works smoothly. Thank you!
