### ISSUE TITLE
Safari Issue

### ISSUE THREAD

**Issue by SmoochySix4** [baptistecdr/aria2-extensions#30]
I tried to compile and run. While running, the app wants the information to connect to the aria daemon. When I give it and click save, this is the output in Xcode:

`2022-01-25 07:53:46.455997-0500 Aria2 Integration[34774:619952] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x600002071200> (Domain: group.bosp.Aria2-Integration, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
2022-01-25 07:53:46.586044-0500 Aria2 Integration[34774:619952] Metal API Validation Enabled
2022-01-25 07:53:51.499543-0500 Aria2 Integration[34774:619952] [logging-persist] cannot open file at line 45340 of [d24547a13b]
2022-01-25 07:53:51.499574-0500 Aria2 Integration[34774:619952] [logging-persist] os_unix.c:45340: (0) open(/var/db/DetachedSignatures) - Undefined error: 0`

**Comment by baptistecdr** [comment]
Hello,

I updated the extension in order to fix your problem. Tell me if it's still the case.
Also, here you can find the signed app, sorry for the icon not following Big Sur+ style guideline. I contacted someone to create a new icon.

[Aria2 Integration.app.zip](https://github.com/baptistecdr/aria2-extensions/files/8055717/Aria2.Integration.app.zip)

**Comment by Balooforever** [comment]
Hi, this app doesn't work for me, I can save but can't send a link to the app : nw_connection_report_state_with_handler_on_nw_queue [C10] reporting state cancelled error Connection refused

I don't understand why, Firefox Extension work great in my system.
