### ISSUE TITLE
Bypass without generation of "Canceled Message" in Fx Download log

### ISSUE THREAD

**Issue by gbcox** [baptistecdr/aria2-extensions#8]
I'm currently routing all downloads to Aria2, so each time I use the "Fx Save As" dialog, it properly transfers the new name/location to aria2, however then generates a cancelled message in the internal Fx log.  I like the way you're integrating the use of the Fx dialogs, it makes the add-on much nicer and more native-like to use.  The filling up that log is a bit of a drag though.  If it can't be fixed, no worries... just a suggestion.  

This request also might tie in with issue #6.  As far as I can tell, the only advantage of having a separate dialog would be to get around the log issue, and using the Fx built in stuff IMO is much better.

**Comment by baptistecdr** [comment]
Hello,

Thank you again, I just pushed an update with this commit [d5f8caa](https://github.com/baptistecdr/aria2-extensions/commit/73a194e070f9a3b2aee915798f1ac2018b046868). It removes from history the downloaded file. 🙂

And yes, I prefer to use Firefox/Chrome dialog rather than implementing one because for the moment, the API provide enough functionality and It respects the OS's UI. 👍🏻

Best regards,
baptistecdr

**Comment by gbcox** [comment]
Thanks for fast fix.  I'll keep testing but as far as I can tell after testing for over an hour, with multiple websites this morning, it works great.  If I notice anything else, I'll open another bug.  Thanks again!
